import { Navbar } from "@/components/Navbar";
import { Card } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";

const TermsOfService = () => {
  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      
      <div className="container mx-auto px-4 py-24 md:py-28 max-w-4xl">
        <h1 className="text-4xl font-bold mb-4">Terms of Service</h1>
        <p className="text-muted-foreground mb-8">Last updated: October 23, 2025</p>
        
        <Card className="p-8 glass-card border-border/50 space-y-6">
          <section>
            <h2 className="text-2xl font-semibold mb-3">Agreement to Terms</h2>
            <p className="text-muted-foreground">
              By accessing or using AI Image Studio ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-2xl font-semibold mb-3">Use of Service</h2>
            <div className="space-y-3 text-muted-foreground">
              <p>You may use the Service to generate AI-powered images based on text prompts. By using the Service, you agree to:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Provide accurate and complete information when creating an account</li>
                <li>Maintain the security of your account credentials</li>
                <li>Not use the Service for any illegal or unauthorized purpose</li>
                <li>Not generate content that is harmful, offensive, or violates others' rights</li>
                <li>Not attempt to bypass any limitations or restrictions on the Service</li>
                <li>Comply with all applicable laws and regulations</li>
              </ul>
            </div>
          </section>

          <Separator />

          <section>
            <h2 className="text-2xl font-semibold mb-3">Account Responsibilities</h2>
            <p className="text-muted-foreground">
              You are responsible for maintaining the confidentiality of your account and password. You agree to accept responsibility for all activities that occur under your account. We reserve the right to refuse service, terminate accounts, or remove content at our sole discretion.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-2xl font-semibold mb-3">Content Ownership and Rights</h2>
            <div className="space-y-3 text-muted-foreground">
              <p><strong>Your Content:</strong> You retain ownership of the prompts you create and the resulting images generated by the Service.</p>
              <p><strong>License to Us:</strong> By using the Service, you grant us a license to store, process, and display your content as necessary to provide the Service.</p>
              <p><strong>AI-Generated Content:</strong> Images generated through the Service are created by AI models. While you have rights to use these images, they may not be eligible for copyright protection in all jurisdictions.</p>
            </div>
          </section>

          <Separator />

          <section>
            <h2 className="text-2xl font-semibold mb-3">Prohibited Content</h2>
            <p className="text-muted-foreground mb-3">You may not use the Service to generate or share content that:</p>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
              <li>Violates any laws or regulations</li>
              <li>Infringes on intellectual property rights</li>
              <li>Contains hate speech, harassment, or threats</li>
              <li>Depicts illegal activities or violence</li>
              <li>Is sexually explicit or contains nudity</li>
              <li>Attempts to impersonate others or spread misinformation</li>
              <li>Contains malware or harmful code</li>
            </ul>
          </section>

          <Separator />

          <section>
            <h2 className="text-2xl font-semibold mb-3">Service Availability</h2>
            <p className="text-muted-foreground">
              We strive to provide reliable service, but we do not guarantee that the Service will be available at all times or error-free. We reserve the right to modify, suspend, or discontinue the Service at any time without notice.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-2xl font-semibold mb-3">Limitation of Liability</h2>
            <p className="text-muted-foreground">
              To the fullest extent permitted by law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service. Our total liability shall not exceed the amount you paid for the Service in the past 12 months.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-2xl font-semibold mb-3">Disclaimer of Warranties</h2>
            <p className="text-muted-foreground">
              The Service is provided "as is" and "as available" without warranties of any kind, either express or implied. We do not warrant that the Service will meet your requirements or that it will be uninterrupted, secure, or error-free.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-2xl font-semibold mb-3">Indemnification</h2>
            <p className="text-muted-foreground">
              You agree to indemnify and hold us harmless from any claims, damages, losses, or expenses arising from your use of the Service, violation of these Terms, or infringement of any third-party rights.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-2xl font-semibold mb-3">Advertising</h2>
            <p className="text-muted-foreground">
              The Service may display advertisements. By using the Service, you agree to the display of such advertisements as part of the user experience.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-2xl font-semibold mb-3">Changes to Terms</h2>
            <p className="text-muted-foreground">
              We reserve the right to modify these Terms at any time. We will notify users of any material changes by posting the new Terms on this page and updating the "Last updated" date. Your continued use of the Service after such changes constitutes acceptance of the new Terms.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-2xl font-semibold mb-3">Governing Law</h2>
            <p className="text-muted-foreground">
              These Terms shall be governed by and construed in accordance with applicable laws, without regard to conflict of law provisions.
            </p>
          </section>

          <Separator />

          <section>
            <h2 className="text-2xl font-semibold mb-3">Contact Information</h2>
            <p className="text-muted-foreground">
              If you have any questions about these Terms of Service, please contact us through your account settings or by reaching out to our support team.
            </p>
          </section>
        </Card>
      </div>
    </div>
  );
};

export default TermsOfService;
